const PDFDocument = require("pdfkit");

/* ================= GENERATE RESULT PDF ================= */
function generateResultPDF(result) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 40 });
    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    const passFail = result.percentage >= 40 ? "PASS" : "FAIL";

    /* ================= HEADER ================= */
    doc.fontSize(18).text("SM QUIZ PLATFORM", { align: "center" });
    doc.moveDown(0.3);
    doc.fontSize(14).text("Exam Result Report", { align: "center" });
    doc.moveDown(1.5);

    /* ================= USER INFO ================= */
    doc.fontSize(11);
    doc.text(`Name: ${result.userName || "N/A"}`);
    doc.text(`Email: ${result.email || "N/A"}`);
    doc.text(`Subject: ${result.subjectName}`);
    doc.text(`Date: ${new Date().toLocaleString()}`);
    doc.text(`Time Taken: ${result.timeTakenSec || 0} sec`);
    doc.moveDown(1);

    /* ================= SUMMARY ================= */
    doc.fontSize(12).text("Result Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Total Questions: ${result.total}`);
    doc.text(`Attempted: ${result.attempted}`);
    doc.text(`Correct: ${result.correct}`);
    doc.text(`Wrong: ${result.wrong}`);
    doc.text(`Score: ${result.score}`);
    doc.text(`Percentage: ${result.percentage}%`);
    doc.text(`Result: ${passFail}`);
    doc.moveDown(1.5);

    /* ================= QUESTIONS ================= */
    doc.fontSize(13).text("Answer Details", { underline: true });
    doc.moveDown();

    result.questions.forEach((q, i) => {
      if (doc.y > 750) doc.addPage();

      const questionText =
        q.question || q.title || `Question ${i + 1}`;

      // 🔐 SAFE ANSWER FETCH (object or array)
      const userAnswerIndex =
        result.answers?.[q._id] ?? result.answers?.[i];

      const correctIndex = q.correctAnswer ?? q.answer;

      doc
        .fontSize(11)
        .fillColor("#000")
        .text(`Q${i + 1}. ${questionText}`, {
          paragraphGap: 4,
        });

      /* CODE QUESTION */
      if (q.type === "output" && q.code?.content) {
        doc
          .moveDown(0.3)
          .font("Courier")
          .fontSize(10)
          .fillColor("#111")
          .text(q.code.content, {
            indent: 20,
            paragraphGap: 6,
          })
          .font("Helvetica");
      }

      /* USER ANSWER */
      doc.fontSize(10).text(
        `Your Answer: ${userAnswerIndex !== undefined
          ? q.options?.[userAnswerIndex]
          : "Not Attempted"
        }`,
        { indent: 20 }
      );

      /* CORRECT ANSWER */
      doc.fontSize(10).text(
        `Correct Answer: ${q.options?.[correctIndex]}`,
        { indent: 20 }
      );

      doc.moveDown(1);
    });

    /* ================= FOOTER ================= */
    doc.moveDown(1);
    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        "Generated by SM Quiz Platform",
        { align: "center" }
      );

    doc.end();
  });
}

module.exports = generateResultPDF;
